<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CampaignReportDetailSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Campaign Running
        DB::table('campaign_report_details')->insert([
            [
            'id' => "979789c4-bcd5-4feb-9633-f5355ea5b112",
            'date' => '2023-07-08',
            'amount' => 1000000,
            'description' => 'Modal crowdfunding',
            'evidence' => 'https://www.instagram.com/rhmfzh._/',
            'type' => 'Pemasukkan',
            'created_by' => 'system',
            'updated_by' => 'system',
            'is_deleted' => false,
            'version' => 1,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'id' => "747ded3a-a075-4af1-aa33-04f4693f7b23",
            'date' => '2023-07-09',
            'amount' => 200000,
            'description' => 'Pembelian tepung',
            'evidence' => 'https://www.instagram.com/rhmfzh._/',
            'type' => 'Pengeluaran',
            'created_by' => 'system',
            'updated_by' => 'system',
            'is_deleted' => false,
            'version' => 1,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
                'id' => "d7880e3b-f6af-4490-94da-5286f4c291df",
                'date' => '2023-07-10',
                'amount' => 300000,
                'description' => 'Pembelian telur',
                'evidence' => 'https://www.instagram.com/rhmfzh._/',
                'type' => 'Pengeluaran',
                'created_by' => 'system',
                'updated_by' => 'system',
                'is_deleted' => false,
                'version' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => "fbb7b0b8-e0c0-44b0-9be9-8681bd59b858",
                'date' => '2023-07-11',
                'amount' => 2000000,
                'description' => 'Penjualan ke pt sejahtera selamanya',
                'evidence' => 'https://www.instagram.com/rhmfzh._/',
                'type' => 'Pemasukkan',
                'created_by' => 'system',
                'updated_by' => 'system',
                'is_deleted' => false,
                'version' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => "90a773d5-10d0-41f0-a203-1252eddfa032",
                'date' => '2023-07-12',
                'amount' => 500000,
                'description' => 'Gaji karyawan',
                'evidence' => 'https://www.instagram.com/rhmfzh._/',
                'type' => 'Pengeluaran',
                'created_by' => 'system',
                'updated_by' => 'system',
                'is_deleted' => false,
                'version' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => "316e9617-e20f-45f7-a76d-f98c0d2fc1da",
                'date' => '2023-07-13',
                'amount' => 750000,
                'description' => 'Pengembalian dana pertama',
                'evidence' => 'https://www.instagram.com/rhmfzh._/',
                'type' => 'Pengeluaran',
                'created_by' => 'system',
                'updated_by' => 'system',
                'is_deleted' => false,
                'version' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Campaign Done Part 1
            [
                'id' => "7e6d3efd-df6b-4504-96e8-e157d3b70bf0",
                'date' => '2023-07-08',
                'amount' => 1000000,
                'description' => 'Modal crowdfunding',
                'evidence' => 'https://www.instagram.com/rhmfzh._/',
                'type' => 'Pemasukkan',
                'created_by' => 'system',
                'updated_by' => 'system',
                'is_deleted' => false,
                'version' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                ],
                [
                'id' => "8885ab25-27ee-402e-bf01-753123dbc47a",
                'date' => '2023-07-09',
                'amount' => 200000,
                'description' => 'Pembelian tepung',
                'evidence' => 'https://www.instagram.com/rhmfzh._/',
                'type' => 'Pengeluaran',
                'created_by' => 'system',
                'updated_by' => 'system',
                'is_deleted' => false,
                'version' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                ],
                [
                    'id' => "6a16aaf5-f24a-43da-bf21-0c6235d7bc89",
                    'date' => '2023-07-10',
                    'amount' => 300000,
                    'description' => 'Pembelian telur',
                    'evidence' => 'https://www.instagram.com/rhmfzh._/',
                    'type' => 'Pengeluaran',
                    'created_by' => 'system',
                    'updated_by' => 'system',
                    'is_deleted' => false,
                    'version' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => "d84e9ee8-fff9-42ce-abad-e4b64454ee65",
                    'date' => '2023-07-11',
                    'amount' => 2000000,
                    'description' => 'Penjualan ke pt sejahtera selamanya',
                    'evidence' => 'https://www.instagram.com/rhmfzh._/',
                    'type' => 'Pemasukkan',
                    'created_by' => 'system',
                    'updated_by' => 'system',
                    'is_deleted' => false,
                    'version' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => "359c8d4f-84a0-4525-83cd-a7bef6900fc6",
                    'date' => '2023-07-12',
                    'amount' => 500000,
                    'description' => 'Gaji karyawan',
                    'evidence' => 'https://www.instagram.com/rhmfzh._/',
                    'type' => 'Pengeluaran',
                    'created_by' => 'system',
                    'updated_by' => 'system',
                    'is_deleted' => false,
                    'version' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => "2a6bba81-bdf8-4195-850e-6111c0a2fa64",
                    'date' => '2023-07-13',
                    'amount' => 750000,
                    'description' => 'Pengembalian dana pertama',
                    'evidence' => 'https://www.instagram.com/rhmfzh._/',
                    'type' => 'Pengeluaran',
                    'created_by' => 'system',
                    'updated_by' => 'system',
                    'is_deleted' => false,
                    'version' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                // Campaign Done Part 2
                [
                    'id' => "120a41f9-4ee2-48c2-a1b7-a071aaf01ce9",
                    'date' => '2023-07-08',
                    'amount' => 125000,
                    'description' => 'Sisa keuangan',
                    'evidence' => 'https://www.instagram.com/rhmfzh._/',
                    'type' => 'Pemasukkan',
                    'created_by' => 'system',
                    'updated_by' => 'system',
                    'is_deleted' => false,
                    'version' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => "be4a79ed-259a-4c4c-87f4-b1e012bb050f",
                    'date' => '2023-07-09',
                    'amount' => 200000,
                    'description' => 'Pembelian tepung',
                    'evidence' => 'https://www.instagram.com/rhmfzh._/',
                    'type' => 'Pengeluaran',
                    'created_by' => 'system',
                    'updated_by' => 'system',
                    'is_deleted' => false,
                    'version' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => "c3b702a4-672e-4cba-ba32-93b37b815c0a",
                    'date' => '2023-07-10',
                    'amount' => 300000,
                    'description' => 'Pembelian telur',
                    'evidence' => 'https://www.instagram.com/rhmfzh._/',
                    'type' => 'Pengeluaran',
                    'created_by' => 'system',
                    'updated_by' => 'system',
                    'is_deleted' => false,
                    'version' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => "c083b298-1127-4209-84f5-b7d3cb00d63a",
                    'date' => '2023-07-11',
                    'amount' => 3000000,
                    'description' => 'Penjualan ke pt sejahtera selamanya',
                    'evidence' => 'https://www.instagram.com/rhmfzh._/',
                    'type' => 'Pemasukkan',
                    'created_by' => 'system',
                    'updated_by' => 'system',
                    'is_deleted' => false,
                    'version' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => "86fff8fd-c588-470d-96c9-1840c46c5976",
                    'date' => '2023-07-12',
                    'amount' => 500000,
                    'description' => 'Gaji karyawan',
                    'evidence' => 'https://www.instagram.com/rhmfzh._/',
                    'type' => 'Pengeluaran',
                    'created_by' => 'system',
                    'updated_by' => 'system',
                    'is_deleted' => false,
                    'version' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'id' => "8189ed07-b1bb-4221-8e29-32dedd276ea9",
                    'date' => '2023-07-13',
                    'amount' => 750000,
                    'description' => 'Pengembalian dana kedua',
                    'evidence' => 'https://www.instagram.com/rhmfzh._/',
                    'type' => 'Pengeluaran',
                    'created_by' => 'system',
                    'updated_by' => 'system',
                    'is_deleted' => false,
                    'version' => 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
        ]);
    }
}
